name: 'Check WCSLIB release'
description: 'Open issue if WCSLIB has a new release.'
author: 'pllim'
inputs:
  WCSLIB_CHECK_N_DAYS:
    description: 'Only a release made in this last N number of days counts as new'
    default: 7
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
